[project]
authors = [
  {name = "Jaseem Abid", email = "me@jabid.in"},
]
dependencies = [
    "esphome>=2025.12.5",
]
description = ""
name = "espconfig"
readme = "README.md"
requires-python = "==3.13.11"
version = "0.1.0"
